config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "home/minor"

  root to: 'companies#index'
  
  resources :companies do
    collection do
      get 'search'
      post 'import'
      get 'export'
      post 'export'
    end
    resources :contacts
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :company
  has_and_belongs_to_many :contact_types
end

app/models/contact_type.rb
class ContactType < ApplicationRecord
  has_and_belongs_to_many :contacts
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @company = Company.find(params[:company_id])
    @contacts = Company.find(params[:company_id]).contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    #company = Company.find(params[:company_id])
    #@contact = company.contacts.find(params[:id])
  end

  # GET /contacts/new
  def new
    @company = Company.find(params[:company_id])
    @contact = Company.find(params[:company_id]).contacts.build
    
    #@contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
    @company = Company.find(params[:company_id])
    @contact = Company.find(params[:company_id]).contacts.find(params[:id])
    #@contact = company.contacts.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    company = Company.find(params[:company_id])
    @contact = company.contacts.create(contact_params)
    #@contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to [@contact.company, @contact], notice: 'El contacto fue creado exitosamente.' }
        format.json { render :show, status: :created, location: [@contact.company, @contact] }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    company = Company.find(params[:company_id])
    @contact = company.contacts.find(params[:id])

    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to [@contact.company, @contact], notice: 'El contacto fue editado exitosamente.' }
        format.json { render :show, status: :ok, location: [@contact.company, @contact] }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    company = Company.find(params[:company_id])
    @contact = company.contacts.find(params[:id])
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to company_contacts_url, notice: 'El contacto fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :position, :phone, :cellphone, :email, :other_email, :company_id, contact_type_ids:[])
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for([contact.company, contact], html: {class: "form-horizontal"}) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nombre", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :position, "Posición", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :position, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :phone, "Teléfono Fijo", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :phone, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :cellphone, "Teléfono Móvil", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :cellphone, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, "Email", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :email, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :other_email, "Email 2", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :other_email, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :contact_type, "Contacto Para", class: "col-lg-2 control-label" %>
    <div class="col-lg-10 checkbox-activity-type">
      <%= f.collection_check_boxes(:contact_type_ids, ContactType.all, :id, :name, {}, {:class => ''}) %>
    </div>
  </div>

  <div class="hr-line-dashed"></div>

  <div class="form-group actions">
    <div class="col-lg-10 col-lg-offset-2">
      <%= f.submit "Guardar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="ibox float-e-margins m-t">
  <div class="ibox-title">
    <h3>Editar Contacto</h3>
    <h4><%= @company.name %></h4>
  </div>

  <div class="ibox-content">

	<%= render 'form', contact: @contact %>

	<%= link_to 'Ver', [@contact.company, @contact] %> | 
	<%= link_to 'Regresar', company_contacts_path %>
	
  </div>
</div>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="ibox float-e-margins m-t">

  <div class="ibox-title">
    <h3>Contactos</h3>
    <h4><%= @company.name %></h4>
  </div>

  <div class="ibox-content">

    <table class="table table-striped m-t">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Posición</th>
          <th>Email</th>
          <th>Contacto Para</th>
          <th>Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @contacts.each do |contact| %>
          <tr class="border-left-right">
            <td><%= contact.name %></td>
            <td><%= contact.position %></td>
            <td><%= contact.email %></td>
            <td>
              <%
              arr_contact_types = []
              contact.contact_types.each do |contact_type|
                arr_contact_types << contact_type.name
              end
              str_contact_types = arr_contact_types.join(", ")
              %>
              <%= str_contact_types %>
            </td>
            <td class="font-awesome-14">
            <%= link_to '<i class="fa fa-plus-square"></i>'.html_safe, [contact.company, contact], class: "m-r-sm" %> 
            <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_company_contact_path(contact.company, contact), class: "m-l-sm m-r-sm" %>
            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, [contact.company, contact], method: :delete, data: { confirm: 'Estás seguro?' }, class: "m-l-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Nuevo Contacto', new_company_contact_path %> | 
    <%= link_to 'Regresar', companies_path %>

  </div>

</div>

app/views/contacts/new.html.erb
<div class="ibox float-e-margins m-t">
  <div class="ibox-title">
    <h3>Nuevo Contacto</h3>
    <h4><%= @company.name %></h4>
  </div>

  <div class="ibox-content">

	<%= render 'form', contact: @contact %>

	<%= link_to 'Regresar', company_contacts_path %>

  </div>
</div>

app/views/contacts/show.html.erb
<div class="ibox float-e-margins m-t">
  <div class="ibox-title">
    <h3>Contacto</h3>
  </div>

  <div class="ibox-content">

    <p id="notice"><%= notice %></p>

    <%= form_tag("", class: 'form-horizontal') do %>
      <div class="form-group">
        <%= label_tag :name, "Nombre", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :name, @contact.name, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :position, "Posición", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :position, @contact.position, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :phone, "Teléfono Fijo", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :phone, @contact.phone, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :cellphone, "Teléfono Móvil", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :cellphone, @contact.cellphone, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :email, "Email", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :email, @contact.email, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :other_email, "Email 2", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :other_email, @contact.other_email, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :contact_types, "Contacto Para", class: "col-lg-2 control-label" %>
        <%
        arr_contact_types = []
        @contact.contact_types.each do |contact_type|
          arr_contact_types << contact_type.name
        end
        str_contact_types = arr_contact_types.join(", ")
        %>
        <div class="col-lg-10">
        <%= text_field_tag :contact_types, str_contact_types, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :company, "Empresa", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :company, @contact.company.name, class: 'form-control' %>
        </div>
      </div>
    <% end %>

    <br>
    
    <%= link_to 'Editar', edit_company_contact_path(@contact.company, @contact) %> |
    <%= link_to 'Regresar', company_contacts_path(@contact.company) %>

  </div>
</div>