config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "home/minor"

  root to: 'companies#index'
  
  resources :companies do
    collection do
      get 'search'
      post 'import'
      get 'export'
      post 'export'
    end
    resources :contacts
  end

end

app/models/company.rb
require 'spreadsheet'

class Company < ApplicationRecord
  belongs_to :country
  has_and_belongs_to_many :activity_types
  has_and_belongs_to_many :product_categories
  has_many :contacts

  def self.import(file)
    num_companies_imported = 0
    
  	Spreadsheet.client_encoding = 'UTF-8'
  	book = Spreadsheet.open file.path
  	sheet1 = book.worksheet 0
  	sheet1.each 1 do |row|
  	  company = Company.find_by(ruc: row[1])
      activity_ids = []
      category_ids = []

  	  if !company
  	  	country = Country.find_by(name: row[6].strip.capitalize)
        
        if row[4]
          arr_activities = row[4].strip.split(',')
          arr_activities.each do |activity|
            obj_activity = ActivityType.find_by(name: activity.capitalize)
            activity_ids << obj_activity.id
          end
        end

        if row[5]
          arr_categories = row[5].strip.split(',')
          arr_categories.each do |category|
            obj_category = ProductCategory.find_by(name: category.capitalize)
            category_ids << obj_category.id
          end
        end

        company_created = Company.create(ruc: row[1].to_s.strip, name: row[2], short_name: row[3], country_id: country.id, activity_type_ids: activity_ids, product_category_ids: category_ids)
        if company_created
          num_companies_imported += 1
        end
  	  end
    end
    return num_companies_imported
  end

  def self.export(country_id,activity_type_id,product_category_id)
    xls_report = StringIO.new

    Spreadsheet.client_encoding = 'UTF-8'
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet

    sheet1.row(0).push "Ruc", "Nombre Empresa", "Nombre Corto", "Nombre Comercial", "Direccion", "Email", "Website", "Fundacion", "Tipo Actividad", "Linea Producto", "Pais", "Contacto", "Posicion", "Telefono Fijo", "Telefono Movil", "Email", "Contacto para"
    i = 1;

    companies = Company
                .select("companies.ruc, companies.name as c_name, companies.short_name, companies.trade_name, companies.address, companies.email, companies.website, companies.foundation, companies.country_id, activity_types.name as at_name, product_categories.name as pc_name, contacts.id as co_id, contacts.name as co_name, contacts.position, contacts.phone, contacts.cellphone, contacts.email as co_email")
                .joins(:activity_types, :product_categories)
                .left_outer_joins(:contacts)
                .where("companies.country_id = ? AND activity_types.id = ? AND product_categories.id = ?", country_id, activity_type_id, product_category_id)
    companies.each do |company|
      # Obtener pais
      country = Country.find(company.country_id)
      # Obtener contacto
      if company.co_id
        arr_contact_types = []
        contact_types = Contact.find(company.co_id).contact_types
        contact_types.each do |contact_type|
          arr_contact_types << contact_type.name
        end
        str_contact_types = arr_contact_types.join(",")
      end
      sheet1.row(i).push company.ruc, company.c_name, company.short_name, company.trade_name, company.address, company.email, company.website, company.foundation, company.at_name, company.pc_name, country.name, company.co_name, company.position, company.phone, company.cellphone, company.co_email, str_contact_types
      i += 1
    end

    book.write(xls_report)
    xls_report.string

  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    # @companies = Company.where(country_id: 1).order(created_at: :desc).page(params[:page].to_i).per(20)    
  end

  # GET /companies/search
  def search   
    if company_search_param.present?
      @companies = Company.where("country_id = ? AND name ILIKE ?", params[:company][:country_id],"%#{params[:search]}%").order(name: :asc).page(params[:page].to_i).per(20) 
    else
      @companies = Company.where(country_id: params[:company][:country_id]).order(name: :asc).page(params[:page].to_i).per(20) 
    end
  end

  def import
    num_companies_imported = Company.import(params[:file])
    if num_companies_imported > 0
      redirect_to companies_url, notice: "#{num_companies_imported} empresas importadas exitosamente !"
    else
      redirect_to companies_url, notice: "#{num_companies_imported} empresas importadas. Todas las empresas ya existían previamente."
    end
  end

  def export
    if request.post?
      data = Company.export(params[:company][:country_id],params[:company][:activity_type_id],params[:company][:product_category_id])
      send_data(data, :type => "text/xls;charset=utf-8;header=present", :filename => "Reporte.xls")
      #redirect_to companies_url
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'La empresa fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'La empresa fue editada exitosamente.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'La empresa fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:ruc, :name, :short_name, :trade_name, :address, :email, :website, :foundation, :country_id, activity_type_ids:[], product_category_ids:[])
    end

  def company_search_param
    params[:search] || {}
  end

  def company_country_param
    params[:company][:country_id] || {}
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(company, html: {class: "form-horizontal"}) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :ruc, "Ruc", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :ruc, :required => true, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, "Nombre", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, :required => true, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :short_name, "Nombre Corto", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :short_name, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :trade_name, "Nombre Comercial", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :trade_name, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, "Dirección", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :address, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, "Email", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :email, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :website, "Sitio Web", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :website, class: "form-control input-sm" %>
    </div>
  </div>

  <div class="form-group form-inline">
    <%= f.label :foundation, "Fundación", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.date_select :foundation, {:start_year => Date.current.year, :end_year => 1970, prompt: { day: 'Escoger día', month: 'Escoger mes', year: 'Escoger año' }}, {class: "form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :country, "País", class: "col-lg-2 control-label" %>
    <div class="col-lg-3">
      <%= f.collection_select(:country_id, Country.all, :id, :name, {}, {:class => 'form-control'}) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :activity_type, "Tipo de Actividad", class: "col-lg-2 control-label" %>
    <div class="col-lg-10 checkbox-activity-type">
      <%= f.collection_check_boxes(:activity_type_ids, ActivityType.all, :id, :name, {}, {:class => ''}) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :product_category, "Línea de Producto", class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.collection_select(:product_category_ids, ProductCategory.all, :id, :name, {}, {:multiple => true, :class => 'chosen-select-vd'}) %>
    </div>
  </div>

  <div class="hr-line-dashed"></div>
  
  <div class="form-group actions">
    <div class="col-lg-10 col-lg-offset-2">
      <%= f.submit "Guardar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<% content_for :javascript do %>
<script type="text/javascript">
  $(document).ready(function() {
    $(".chosen-select-vd").chosen({
      disable_search_threshold: 10,
      no_results_text: "Oops, nothing found!",
      width: "100%"
    });
  });
</script>
<% end %>

app/views/companies/edit.html.erb
<div class="ibox float-e-margins m-t">
  <div class="ibox-title">
    <h3>Editar Empresa</h3>
  </div>

  <div class="ibox-content">

  <%= render 'form', company: @company %>
  
  <%= link_to 'Ver', @company %> |
  <%= link_to 'Regresar', companies_path %>

  </div>
</div>

app/views/companies/export.html.erb
<p id="notice"><%= notice %></p>

<div class="ibox float-e-margins m-t">

  <div class="ibox-title">
    <h3>Empresas</h3>
  </div>

  <div class="ibox-content">

    <h4>Seleccione los campos para generar un reporte</h4>
    
    <%= form_tag(export_companies_path, method: "post", class: 'form-horizontal') do %>
      
      <div class="form-group">
        <%= label_tag :country, "Pais", class: "col-lg-2 control-label" %>
        <div class="col-lg-4">
          <%= collection_select(:company, :country_id, Country.all, :id, :name, {}, {:class => 'form-control'}) %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :activity_type, "Tipo de Actividad", class: "col-lg-2 control-label" %>
        <div class="col-lg-4">
          <%= collection_select(:company, :activity_type_id, ActivityType.all, :id, :name, {}, {:class => 'form-control'}) %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :product_category, "Línea de Producto", class: "col-lg-2 control-label" %>
        <div class="col-lg-4">
          <%= collection_select(:company, :product_category_id, ProductCategory.all, :id, :name, {}, {:class => 'form-control'}) %>
        </div>
      </div>

      <div class="hr-line-dashed"></div>
  
      <div class="form-group actions">
        <div class="col-lg-10 col-lg-offset-2">
          <%= button_tag "Exportar", class: "btn btn-primary" %>
        </div>
      </div>

    <% end %>

    <br>

    <%= link_to 'Regresar', companies_path %>

  </div>

</div>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="ibox float-e-margins m-t">

  <div class="ibox-title">
    <h3>Empresas
    <%= link_to 'Nueva Empresa', new_company_path, class: "btn btn-primary btn-sm btn-outline m-l-lg" %>
    <button type="button" class="btn btn-danger btn-sm btn-outline" data-toggle="modal" data-target="#myModal">
        Cargar Archivos
    </button>
    <%= link_to 'Generar Reportes', export_companies_path, class: "btn btn-warning btn-sm btn-outline" %>
    </h3>
  </div>

  <div class="ibox-content">

    <%= form_tag(search_companies_path, method: "get", class: 'form-horizontal') do %>
      <div class="form-group">
        <div class="col-md-3">
        <%= collection_select(:company, :country_id, Country.all, :id, :name, {}, {:class => 'form-control'}) %>
        </div>
        <div class="col-md-7">
        <%= text_field_tag :search, "", placeholder: "Nombre de la empresa", class: 'form-control' %>
        </div>
        <div class="col-md-2">
        <%= button_tag "Buscar", class: 'btn btn-primary btn-block' %>
        </div>
      </div>
    <% end %>   
    
    <br>

    <div class="modal inmodal" id="myModal" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
      <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
              <div class="modal-header">
                <h4 class="modal-title">Cargar Archivos</h4>
                <small class="font-bold">Adjunta un archivo de excel en formato xls</small>
              </div>
              <div class="modal-body">
                <%= form_tag(import_companies_path, multipart: true, class: 'form-horizontal') do %>
                  <div class="form-group">
                    <div class="col-md-8">
                    <%= file_field_tag :file, :required => true %>
                    </div>
                    <div class="col-md-4">
                    <%= submit_tag "Importar", class: 'btn btn-primary' %>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-white" data-dismiss="modal">Cancelar</button>
              </div>
          </div>
      </div>
    </div>

  </div>

</div>

app/views/companies/new.html.erb
<div class="ibox float-e-margins m-t">
  <div class="ibox-title">
    <h3>Nueva Empresa</h3>
  </div>

  <div class="ibox-content">

  <%= render 'form', company: @company %>

  <%= link_to 'Regresar', companies_path %>
  
  </div>
</div>

app/views/companies/search.html.erb
<p id="notice"><%= notice %></p>

<div class="ibox float-e-margins m-t">

  <div class="ibox-title">
    <h3>Empresas
    <%= link_to 'Nueva Empresa', new_company_path, class: "btn btn-primary btn-sm btn-outline m-l-lg" %>
    <button type="button" class="btn btn-danger btn-sm btn-outline" data-toggle="modal" data-target="#myModal">
        Cargar Archivos
    </button>
    <%= link_to 'Generar Reportes', export_companies_path, class: "btn btn-warning btn-sm btn-outline" %>
    </h3>
  </div>

  <div class="ibox-content">

  <%= form_tag(search_companies_path, method: "get", class: 'form-horizontal') do %>
    <div class="form-group">
      <div class="col-md-3">
      <%= collection_select(:company, :country_id, Country.all, :id, :name, {:selected => params[:company][:country_id]}, {:class => 'form-control'}) %>
      </div>
      <div class="col-md-7">
      <%= text_field_tag :search, params[:search], placeholder: "Nombre de la empresa", class: 'form-control' %>
      </div>
      <div class="col-md-2">
      <%= button_tag "Buscar", class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  <% end %>

    
    <table class="table table-striped m-t">
      <thead>
        <tr>
          <th width="50%">Nombre Empresa</th>
          <th width="50%">Acciones</th>
        </tr>
      </thead>

      <tbody>
        <% @companies.each do |company| %>
          <tr class="border-left-right">
            <td><%= company.name %></td>
            <td class="font-awesome-14">
            <%= link_to '<i class="fa fa-user"></i>'.html_safe, company_contacts_path(company), class: "m-r-sm" %>
            <%= link_to '<i class="fa fa-plus-square"></i>'.html_safe, company, class: "m-l-sm m-r-sm" %>
            <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_company_path(company), class: "m-l-sm m-r-sm" %>
            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, company, method: :delete, data: { confirm: 'Estás seguro?' }, class: "m-l-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

     <%= paginate @companies, :theme => 'twitter-bootstrap-3' %>

    <br>

    <div class="modal inmodal" id="myModal" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
      <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
              <div class="modal-header">
                <h4 class="modal-title">Cargar Archivos</h4>
                <small class="font-bold">Adjunta un archivo de excel en formato xls</small>
              </div>
              <div class="modal-body">
                <%= form_tag(import_companies_path, multipart: true, class: 'form-horizontal') do %>
                  <div class="form-group">
                    <div class="col-md-8">
                    <%= file_field_tag :file, :required => true %>
                    </div>
                    <div class="col-md-4">
                    <%= submit_tag "Importar", class: 'btn btn-primary' %>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Cancelar</button>
              </div>
          </div>
      </div>
    </div>

  </div>

</div>

app/views/companies/show.html.erb
<div class="ibox float-e-margins m-t">
  <div class="ibox-title">
    <h3>Empresa</h3>
  </div>

  <div class="ibox-content">

    <p id="notice"><%= notice %></p>

    <%= form_tag("", class: 'form-horizontal') do %>
      <div class="form-group">
        <%= label_tag :ruc, "Ruc", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :ruc, @company.ruc, class: 'form-control input-sm' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :name, "Nombre", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :name, @company.name, class: 'form-control input-sm' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :short_name, "Nombre Corto", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :short_name, @company.short_name, class: 'form-control input-sm' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :trade_name, "Nombre Comercial", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :trade_name, @company.trade_name, class: 'form-control input-sm' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :address, "Dirección", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :address, @company.address, class: 'form-control input-sm' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :email, "Email", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :email, @company.email, class: 'form-control input-sm' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :website, "Sitio Web", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :website, @company.website, class: 'form-control input-sm' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :foundation, "Fundación", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :foundation, @company.foundation, class: 'form-control input-sm' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :country, "País", class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
        <%= text_field_tag :country, @company.country.name, class: 'form-control input-sm' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :activity_types, "Tipo de Actividad", class: "col-lg-2 control-label" %>
        <%
        arr_activity_types = []
        @company.activity_types.each do |activity|
          arr_activity_types << activity.name
        end
        str_activity_types = arr_activity_types.join(", ")
        %>
        <div class="col-lg-10">
        <%= text_field_tag :activity_types, str_activity_types, class: 'form-control input-sm' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :product_categories, "Línea de Producto", class: "col-lg-2 control-label" %>
        <%
        arr_product_categories = []
        @company.product_categories.each do |category|
          arr_product_categories << category.name
        end
        str_product_categories = arr_product_categories.join(", ")
        %>
        <div class="col-lg-10">
        <%= text_field_tag :product_categories, str_product_categories, class: 'form-control input-sm' %>
        </div>
      </div>
    <% end %>

    <br>

    <%= link_to 'Editar', edit_company_path(@company) %> |
    <%= link_to 'Regresar', companies_path %>
  
  </div>
</div>